---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:
- name: build-website
  image: jekyll/jekyll:4.2.2
  privileged: false
  volumes:
    - name: jekyll
      path: /srv/jekyll

  commands:
    - whoami
    - pwd
    - ls -al
    - chown -R jekyll:jekyll /drone/src
    - gem install bundler
    - bundle install
    - bundle exec jekyll build --trace
    - ls -a _site/
    - rm _site/docker-compose.yml
    - rsync -h

---
kind: pipeline
type: docker
name: default

steps:
- name: rsync
  image: drillster/drone-rsync
  settings:
    hosts:
      - remote1
      - remote2
    user:
      from_secret: rsync_user
    key:
      from_secret: rsync_key
    source: ./dist
    target: ~/packages
    include:
      - "app.tar.gz"
      - "app.tar.gz.md5"
    exclude:
      - "**.*"
    prescript:
      - cd ~/packages
      - md5sum -c app.tar.gz.md5
      - tar -xf app.tar.gz -C ~/app
    script:
      - cd ~/packages
      - md5sum -c app.tar.gz.md5
      - tar -xf app.tar.gz -C ~/app
