---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

steps:
- name: jekyll-build
  image: jekyll/jekyll:4.2
  volumes:
    - name: jekyll
      path: /srv/jekyll
  commands:
    - gem update --system
    - gem install bundler
    - bundle install
    - bundle exec jekyll build

trigger:
  branch:
  - master
