---
kind: pipeline
type: docker
name: build

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:
- name: build-website
  image: jekyll/jekyll:4.2.2
  privileged: false
  volumes:
    - name: jekyll
      path: /srv/jekyll

  commands:
    - whoami
    - pwd
    - ls -al
    - chown -R jekyll:jekyll /drone/src
    - gem install bundler
    - bundle install
    - bundle exec jekyll build --trace
    - ls -a _site/
    - rm _site/docker-compose.yml
    - tar -czvf www-data.tar.gz _site/*

---
kind: pipeline
type: docker
name: transfer

steps:
- name: transfer-website
  image: drillster/drone-rsync
  settings:
    user: odinzu
    key:
      from_secret: rsync_key
    hosts:
      - remote1
    source: ./dist
    target: ~/packages
    secrets: [ rsync_key ]
