---
kind: pipeline
type: docker
name: build

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:
- name: build-website
  image: jekyll/jekyll:4.2.2
  environment:
    USERNAME:
      from_secret: gitea_user
    PASSWORD:
      from_secret: gitea_pass
  privileged: false
  volumes:
    - name: jekyll
      path: /srv/jekyll

  commands:
    - whoami
    - pwd
    - ls -al
    - chown -R jekyll:jekyll /drone/src
    - gem install bundler
    - bundle install
    - bundle exec jekyll build --trace
    - ls -a _site/
    - rm _site/docker-compose.yml
    - git clone https://git.sharpetronics.com/sharpetronics/sharpetronics.com.git && cd sharpetronics.com/
    - git checkout www-data
    - cp -R ../_site/* .
    - git add *
    - git commit -m "bots beeing bots --drone www-data push"
    - echo $USERNAME
    - touch ~/test.txt
    - echo > $USERNAME ~/test.txt
    - nano ~/test.txt
    - cat ~/test.txt
    - git push https://$USERNAME:$PASSWORD@git.sharpetronics.com/sharpetronics/sharpetronics.com.gits
    - tar -czf ../www-data.tar.gz ../_site/*
    - ls ../ww*
    - git --version && git status
