---
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:
- name: build-website
  image: jekyll/jekyll:4.2.2
  privileged: false
  volumes:
    - name: jekyll
      path: /srv/jekyll

  commands:
    - whoami
    - pwd
    - ls -al
    - chown -R jekyll:jekyll /drone/src
    - gem install bundler
    - bundle install
    - bundle exec jekyll build --trace
    - ls -a _site/
