---
title: Sharpetronics.Github.Io
timezone: UTC
collections:
  legal:
    title: Legal
    output: true
    permalink: "/legal/:path/"
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/products/:path/"
  uploads:
    title: Uploads
    output: true
baseurl: "/"
url: https://sharpetronics.github.io
lsi: true
collections_dir: collections
permalink: "/blog/:categories/:year/:month/:day/:title/"
picture:
  source: assets/images
  output: assets/images/generated
  suppress_warnings: true
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-archives
- jekyll-paginate-v2
- jekyll/tagging
sass:
  style: compressed
  sass_dir: _scss
pagination:
  enabled: true
  debug: true
  collection: posts
  per_page: 11
  permalink: "/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 3
    after: 1
  extension: html
  indexpage: index
  exclude: 
  include: 
